Upgrading artifacts to APIM 3.2.0 and updating readme files
wso2/k8s-api-operator pull request #448
Opened 2020-08-28 14:56 UTC by Shehanir

## Purpose
> This PR will upgrade the  artifacts to APIM 3.2.0 and update the readme files to api-operator 1.2.0

2020-08-28 14:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/k8s-api-operator?pullRequest=448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/k8s-api-operator?pullRequest=448) before we can accept your contribution.<br/><hr/>**Shehanir** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/k8s-api-operator?pullRequest=448) it.</sub>

2020-08-31 04:49 UTC, pubudu538 requested changes

2020-08-31 04:49 UTC, pubudu538 commented on README.md
> +- Download API controller v3.2.0 or the latest v3.1.x from the [API Manager Tooling web site](https://wso2.com/api-management/tooling/)
v3.1.x should be v3.2.x

2020-08-31 05:27 UTC, Shehanir commented on README.md
> +- Download API controller v3.2.0 or the latest v3.1.x from the [API Manager Tooling web site](https://wso2.com/api-management/tooling/)
added the changes

2020-08-31 05:32 UTC, pubudu538 approved these changes

2020-08-31 05:32 UTC, merged